- name: Extract iVentoy package
  unarchive:
    src: "/tmp/{{ iventoy_tarball }}"
    dest: /tmp
    remote_src: yes

- name: Sync application files
  synchronize:
    src: "/tmp/iventoy-{{ iventoy_version }}/iventoy-{{ iventoy_version }}/"
    dest: "{{ iventoy_install_dir }}/"
    delete: yes
    command: >
      rsync -a
      - "--exclude=data"
      - "--exclude=iso"
      - "--exclude=user"
      - "--exclude=log"
      {{ iventoy_extract_dir }}/iventoy-{{ iventoy_version }}/
      /opt/iventoy/